app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');
Route::resource('/','WelcomeController');
Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');
Route::get('download',function(){
	$file = $_GET['file'];
	return Response::download($file);
});
Route::get('view', function()
{
	$file = $_GET['file'];
	return Redirect::to($file);
});

// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){
Route::resource('users','UsersController');
Route::resource('admin','AdminController');
Route::resource('admin.staffs','StaffsController');
Route::resource('admin.plots','PlotsController');
Route::resource('plots','PlotsController');
Route::resource('agents','AgentsController');
Route::resource('staffs','StaffsController');
Route::resource('payments','PaymentsController');
Route::resource('customers.payments','PaymentsController');
Route::resource('cocuments', 'DocumentsController');
Route::resource('customers', 'CustomersController');
Route::resource('agents.customers', 'CustomersController');
Route::resource('search', 'SearchController');
Route::resource('partners', 'PartnersController');
Route::resource('transactions', 'TransactionsController');
Route::resource('prospectives', 'ProspectivesController');
Route::resource('tenants', 'TenantsController');
Route::resource('tenants.payments', 'TenanPaymentsController');
Route::resource('land-lords', 'LandlordsController');
Route::resource('compounds', 'CompoundsController');
Route::resource('houses', 'HousesController');
Route::resource('notifications', 'NotificationsController');
Route::get('data-entry', array('as'=>'data_entry', 'uses'=>'PagesController@showData'));
Route::resource('estates', 'EstatesController');
Route::resource('estates.plots', 'EstatesController');
});
#THIS IS THE TESTING PART BELOW
// Event::listen('illuminate.query',function($query){
// echo '<pre style="margin:200px 80px">';
// print_r($query);
// echo '</pre>';
// });

app/views/admin/data_entry.blade.php
<?php #specific page processing
	$studentid = (is_numeric(Request::segment(2)))? Request::segment(2) : 0 ;
	$user_id = Session::get('user_id');
 ?>
@include('templates/top-admin')	
@section('content')
	<div class="cc">
@include('templates/tenants')	
		<div class="pre-container">
			<div class="pre-header">
				<h2>Data Entry</h2>
				<p> lorem lorem lorem lorem </p>
			</div>
			<hr>
			<div class="pre-content">
				<div class="pch">
					<ul>
						<li class="active">
							<span class="pre-icon mega-octicon octicon octicon-file-media"></span>
							<strong class="step"><a href="#">Tenant</a></strong>
							add: land lord, compound, houses and tenant
						</li>
						<li>
							<span class="pre-icon mega-octicon octicon octicon-book"></span>
							<strong class="step"><a href="">Land</a></strong>
							Add: plots, customers, agents
						</li>
						<li>
							<span class="pre-icon mega-octicon octicon octicon-briefcase"></span>
							<strong class="step"><a href="">Staff</a></strong>
							Add: staff, contact, addresses
						</li>
						<li></li>
					</ul>
				</div>
				<div class="forms">
					<div class="add-academics spacer" >
					<h3>Tenant</h3>	
					{{Form::open(array('route'=>'compounds.store','files'=>true,'class'=>'tenant'))}}
					<table class="table table-bordered table-striped table-hover">
						<thead>
							<tr>
								<th colspan="2"><a href="" id="sname" class="trigger" data-type="add-Compound" data-content="forming" data-container="add-academics"><span class="mega-octicon octicon-plus"></span></a>Compound</th>
								<th colspan="3">Land Lord</th>
							</tr>
							<tr>
								<th>address/location</th>
								<th>number of houses</th>
								<th>Fullanme</th>
								<th>Address</th>
								<th>Contacts (phones)</th>
							</tr>
						</thead>
						<tbody>			
							<tr class="forming">
								<td>
									{{Form::text('Compound_location',null,['placeholder'=>'Add Compound location','required'=>1,'autofocus'])}}
								</td>
								<td>
									{{Form::number('Compound_houses',['placeholder'=>'Add Compound of houses','step'=>'any'])}}
								</td>
								<td>
									{{Form::text('fullname',null,['placeholder'=>'land lord name','required'=>1])}}
								</td>
								<td>
									{{Form::text('address',null,['placeholder'=>'Enter address'])}}
								</td>
								<td class="last">
									{{Form::hidden('userid',$user_id)}}
									{{Form::text('contacts',null,['placeholder'=>'Add contact info','required'=>1])}}
									<button type="submit" class="add-mit-right" title="add a Compound you have attended" ><span class="mega-octicon octicon-plus"></span></button>
									<div class="add-doc">
										<span class="octicon octicon-triangle-up"></span>
										<hr>
										{{Form::file('doc',null,['placeholder'=>'Add Docuemnt'])}}
										 <span class="help-block">Only pdf, img, docs.</span>
										<hr>
										<button type="submit" class="btn btn-info">upload a document</button>
									</div>
									<div class="add-subject">
										<span class="octicon octicon-triangle-up"></span>
										<hr>
										<h3>certificate name</h3>
										<hr>
										<div class="subgrad">
											<table>
												<thead>
													<tr>
														<th>Subjects</th>
														<th>Grade</th>
													</tr>
												</thead>
												<tfoot>
													<tr>
														<td rowspan="2">
															<button type="submit" class="btn btn-info">Save subjects</button>
														</td>
													</tr>
												</tfoot>
												<tbody>
													<tr>
														<td><input type="text"></td>
														<td><input type="text"></td>
													</tr>
												</tbody>
											</table>
										</div>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					{{Form::close()}}
					</div> <!-- end of academics -->
					<div class="add-academics spacer work" style="display:none">
					<h3>Land</h3>	
					{{Form::open(array('route'=>'plots.store','files'=>true,'class'=>'upload-prev','id'=>'work'))}}
					<table class="table table-bordered table-striped table-hover">
						<thead>
							<tr>
								<th colspan="5"><a href="" id="sname" class="trigger" data-type="add-Compound" data-content="forming" data-container="add-academics"><span class="mega-octicon octicon-plus"></span></a>Plot</th>
							</tr>
							<tr>
								<th>name</th>
								<th>address/location</th>
								<th>number(D)</th>
								<th>Price</th>

<!-- 								<th>address</th>
								<th></th> -->
							</tr>
						</thead>
						<tbody>			

							<tr class="forming">
								<td>{{Form::text('Compound_name',null,['placeholder'=>'Add Compound name','required'=>1,'autofocus'])}}</td>
								<!-- <td>s</td> -->
								<td>{{Form::text('Compound_name',null,['placeholder'=>'Add Compound location','required'=>1])}}</td>
								<td>
									{{Form::number('Compound_name',['placeholder'=>'Add Compound of houses','step'=>'any'])}}

								</td>
								<td class="last">
									{{Form::hidden('studentID',$studentid)}}
									{{Form::text('certificate_name',null,['placeholder'=>'Add contact info','required'=>1])}}
									<button type="submit" class="add-submit-right" title="add a Compound you have attended" ><span class="mega-octicon octicon-plus"></span></button>
									<div class="add-doc">
										<span class="octicon octicon-triangle-up"></span>
										<hr>
										{{Form::file('doc',null,['placeholder'=>'Add Docuemnt'])}}
										 <span class="help-block">Only pdf, img, docs.</span>
										<hr>
										<button type="submit" class="btn btn-info">upload a document</button>
									</div>
									<div class="add-subject">
										<span class="octicon octicon-triangle-up"></span>
										<hr>
										<h3>certificate name</h3>
										<hr>
										<div class="subgrad">
											<table>
												<thead>
													<tr>
														<th>Subjects</th>
														<th>Grade</th>
													</tr>
												</thead>
												<tfoot>
													<tr>
														<td rowspan="2">
															<button type="submit" class="btn btn-info">Save subjects</button>
														</td>
													</tr>
												</tfoot>
												<tbody>
													<tr>
														<td><input type="text"></td>
														<td><input type="text"></td>
													</tr>
												</tbody>
											</table>
										</div>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					{{Form::close()}}
					</div> <!-- end of work -->
					<div class="add-academics spacer credentials">
					<h3>Credentials</h3>	
					{{Form::open(array('route'=>'plots.store','files'=>true,'class'=>'upload-prev'))}}
						<div class="input-prepend input-append">
						  <span class="add-on">Student Number/ID</span>
						  <input class="span2" id="appendedPrependedInput" type="text">
						  <span class="add-on">#</span>
						</div>
						<div class="form-actions">
						  <button type="submit" class="btn btn-info">Create</button>
						  <button type="button" class="btn btn-success">Generate</button>
						</div>
					{{Form::close()}}
					</div> <!-- end of credentials -->
			<a href="#">skip</a> |
			<a href="#">skip all</a>
		</div> <!-- end of forms -->
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/index.blade.php
@include('templates/top-admin')
@section('content')
	<div class="cc">
		<div class="icons_zone">
			<p>
				<a href="notifications" class="imgthumb">
					<img src="__public/img/notifications.png">
				</a>

				<!-- <a href="notifications">Notifications</a> -->
			</p>
			<p>
				<a href="{{route('prospectives.index')}}" class="imgthumb">
					<!-- <i class="fa fa-tags"></i>  -->
					<img src="__public/img/customers.png">

				</a>
				<!-- <a href="{{route('prospectives.index')}}">Prospective Customers</a> -->
			</p>
			<p>
				<a href="{{route('agents.index')}}" class="imgthumb">
					<!-- <i class="fa fa-users"></i>  -->
					<img src="__public/img/agents.png">

				</a>
				<!-- <a href="{{route('agents.index')}}">Agents</a> -->
			</p>
			<p>
				<a href="{{route('plots.index')}}" class="imgthumb">
					<!-- <i class="fa fa-map-marker"></i> -->
					<img src="__public/img/plots.png">

				</a>
				<!-- <a href="{{route('plots.index')}}">Plots</a> -->
			</p>
			<p>
				<a href="{{route('houses.index')}}" class="imgthumb">
					<!-- <i class="fa fa-building-o"></i> -->
					<img src="__public/img/house.png">

				</a>
				<!-- <a href="{{route('houses.index')}}">Houses</a> -->
			</p>
			<p>
				<a href="{{route('tenants.index')}}" class="imgthumb">
					<!-- <i class="fa fa-key"></i> -->
					<img src="__public/img/tenants.png">

				</a>
				<!-- <a href="{{route('tenants.index')}}">Tenant</a> -->
			</p>
			<p>
				<a href="{{route('data_entry')}}" class="imgthumb">
					<!-- <i class="fa fa-pencil-square-o"></i> -->
					<img src="__public/img/dataentery.png">

				</a>
				<!-- <a href="{{route('data_entry')}}">Data Enty</a> -->
			</p>
			<p>
				<a href="{{route('users.index')}}" class="imgthumb">
					<!-- <i class="fa fa-user"></i> -->
					<img src="__public/img/users.png">

				</a>
				<!-- <a href="{{route('users.index')}}">Users</a> -->
			</p>
		</div><!-- content conent -->	
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/profile.blade.php
@extends('profile')

app/views/admin/search.blade.php
<?php #page specific processing ?>
@include('templates/top-admin')
@section('content')
	<div class="cc">
	<section>
		<?php if (!empty($data)): ?>
			<div class="stats">	
				<a href="#">fetch results</a>
			</div>	
			<hr>
			<ul class="search-results">
				<?php foreach ($data as $key => $value): ?>
				<?php if ($key == 'person' ): ?>
					<?php foreach ($value as $key1 => $value1): ?>
						<li class="result">
							<div class="search-detail">
							<strong>
								<a href="<?php echo 'search/person?pers='.$value1['pers_type'].'&key='.$value1['id']; ?>">
								<?php echo ucwords($value1['pers_fname'].' '.$value1['pers_mname'].' '.$value1['pers_lname']); ?>
								</a>
							</strong>
							<p>
								<span>Person Type : </span> <strong>{{$value1['pers_type']}}</strong> |
								<span>Nationality : </span> <strong>{{$value1['pers_nationality']}}</strong> |
								<span>Gender : </span> <strong>{{$value1['pers_gender']}}</strong> |
							</p>
							</div>
							<hr>
						</li>							
					<?php endforeach ?>
				<?php endif ?>
				<?php if ($key == 'plots' ): ?>
				<?php foreach ($value as $ind => $plot): ?>
				<?php foreach ($plot as $plt => $plo): ?>
					<li class="result">
						<div class="search-detail">
						<strong>
							<a href="{{route('plots.show',$plo['plot_id'])}}">{{e(ucwords($plo['plot_name']))}}</a>
						</strong>
						<p>
							<span>Result Type : </span> <strong>{{e($key)}}</strong> |
							<span>plot size : </span> <strong>{{e($plo['plot_size'])}}</strong> |
							<span>plot price : </span> <strong>{{e($plo['plot_price'])}}</strong> 
						</p>
						</div>
						<hr>
					</li>						
				<?php endforeach ?>
					
				<?php endforeach ?>
				
				<?php endif ?>
				<?php if ($key == 'contact' ): ?>
					<?php foreach ($value as $ind => $cont): ?>
					<?php $perstype = ($cont['person']['pers_type'] == 'Staff')? 'staffs' : 'students'; ?>
						<li class="result">
							<div class="search-detail">
							<strong>
								<a href="<?php echo 'search/person?pers='.$cont['person']['pers_type'].'&key='.$cont['person']['id']; ?>">
								<?php echo ucwords($cont['person']['pers_fname'].' '.$cont['person']['pers_mname'].' '.$cont['person']['pers_lname']); ?>
								</a>
							</strong>
							<p>
								<span>Contact Type : </span> <strong>{{$cont['Cont_ContactType']}}</strong> |
								<span>Contact Info : </span> <strong>{{$cont['Cont_Contact']}}</strong> 
							</p>
							<p>
								<span>Person Type : </span> <strong>{{$cont['person']['pers_type']}}</strong> |
								<span>Nationality : </span> <strong>{{$cont['person']['pers_nationality']}}</strong> |
								<span>Gender : </span> <strong>{{$cont['person']['pers_gender']}}</strong> |
							</p>
							</div>
							<hr>
						</li>						
					<?php endforeach ?>
					
				<?php endif ?>



				<?php if ($key == 'customer' ): ?>
					<?php foreach ($value as $key1 => $value1): ?>
						<li class="result">
							<div class="search-detail">
							<strong>
								<a href="{{route('customers.show',$value1['customers']['cust_id'])}}">
								<?php echo ucwords($value1['pers_fname'].' '.$value1['pers_mname'].' '.$value1['pers_lname']); ?>
								</a>
							</strong>
							<p>
								<span>Person Type : </span> <strong>{{$value1['pers_type']}}</strong> |
								<span>Nationality : </span> <strong>{{$value1['pers_nationality']}}</strong> |
								<span>Gender : </span> <strong>{{$value1['pers_gender']}}</strong> |
							</p>
							</div>
							<hr>
						</li>							
					<?php endforeach ?>
				<?php endif ?>	






				<?php if ($key == 'staff' ): ?>
					<?php foreach ($value as $key1 => $value1): ?>
						<li class="result">
							<div class="search-detail">
							<strong>
								<a href="{{route('staffs.show',$value1['staff']['id'])}}">
								<?php echo ucwords($value1['pers_fname'].' '.$value1['pers_mname'].' '.$value1['pers_lname']); ?>
								</a>
							</strong>
							<p>
								<span>Person Type : </span> <strong>{{$value1['pers_type']}}</strong> |
								<span>Nationality : </span> <strong>{{$value1['pers_nationality']}}</strong> |
								<span>Gender : </span> <strong>{{$value1['pers_gender']}}</strong> |
							</p>
							</div>
							<hr>
						</li>							
					<?php endforeach ?>
				<?php endif ?>	



				<?php if ($key == 'landlord' ): ?>

					<?php foreach ($value as $key1 => $value1): ?>
						<li class="result">
							<div class="search-detail">
							<strong>
								<a href="{{route('land-lords.show',$value1['landlord']['id'])}}">
								<?php echo ucwords($value1['pers_fname'].' '.$value1['pers_mname'].' '.$value1['pers_lname']); ?>
								</a>
							</strong>
							<p>
								<span>Person Type : </span> <strong>{{$value1['pers_type']}}</strong> |
								<span>Nationality : </span> <strong>{{$value1['pers_nationality']}}</strong> |
								<span>Gender : </span> <strong>{{$value1['pers_gender']}}</strong> |
							</p>
							</div>
							<hr>
						</li>							
					<?php endforeach ?>
				<?php endif ?>					


				<?php if ($key == 'tenant' ): ?>
					<?php foreach ($value as $key1 => $value1): ?>
						<li class="result">
							<div class="search-detail">
							<strong>
								<a href="{{route('tenants.show',$value1['tenance']['tent_id'])}}">
								<?php echo ucwords($value1['pers_fname'].' '.$value1['pers_mname'].' '.$value1['pers_lname']); ?>
								</a>
							</strong>
							<p>
								<span>Person Type : </span> <strong>{{$value1['pers_type']}}</strong> |
								<span>Nationality : </span> <strong>{{$value1['pers_nationality']}}</strong> |
								<span>Gender : </span> <strong>{{$value1['pers_gender']}}</strong> |
							</p>
							</div>
							<hr>
						</li>							
					<?php endforeach ?>
				<?php endif ?>	

				<?php if ( $key == 'agent' ): ?>
					<?php foreach ($value as $key1 => $value1): ?>
						<li class="result">
							<div class="search-detail">
							<strong>
								<a href="{{route('agents.show',$value1['agent']['agen_id'])}}">
								<?php echo ucwords($value1['pers_fname'].' '.$value1['pers_mname'].' '.$value1['pers_lname']); ?>
								</a>
							</strong>
							<p>
								<span>Person Type : </span> <strong>{{$value1['pers_type']}}</strong> |
								<span>Nationality : </span> <strong>{{$value1['pers_nationality']}}</strong> |
								<span>Gender : </span> <strong>{{$value1['pers_gender']}}</strong> |
							</p>
							</div>
							<hr>
						</li>							
					<?php endforeach ?>
				<?php endif ?>	


				<?php endforeach; ?>				
			</ul>
			<div class="stats">	
					<a href="#">fetch results</a>
			</div>	
			<?php else: ?>
				<h3>Sorry there were no results</h3>
		<?php endif ?>

	</section>
	</div>
@stop
@include('templates/bottom-admin')