app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');
Route::resource('/','WelcomeController');
Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');
Route::get('download',function(){
	$file = $_GET['file'];
	return Response::download($file);
});
Route::get('view', function()
{
	$file = $_GET['file'];
	return Redirect::to($file);
});

// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){
Route::resource('users','UsersController');
Route::resource('admin','AdminController');
Route::resource('admin.staffs','StaffsController');
Route::resource('admin.plots','PlotsController');
Route::resource('plots','PlotsController');
Route::resource('agents','AgentsController');
Route::resource('staffs','StaffsController');
Route::resource('payments','PaymentsController');
Route::resource('customers.payments','PaymentsController');
Route::resource('cocuments', 'DocumentsController');
Route::resource('customers', 'CustomersController');
Route::resource('agents.customers', 'CustomersController');
Route::resource('search', 'SearchController');
Route::resource('partners', 'PartnersController');
Route::resource('transactions', 'TransactionsController');
Route::resource('prospectives', 'ProspectivesController');
Route::resource('tenants', 'TenantsController');
Route::resource('tenants.payments', 'TenanPaymentsController');
Route::resource('land-lords', 'LandlordsController');
Route::resource('compounds', 'CompoundsController');
Route::resource('houses', 'HousesController');
Route::resource('notifications', 'NotificationsController');
Route::get('data-entry', array('as'=>'data_entry', 'uses'=>'PagesController@showData'));
Route::resource('estates', 'EstatesController');
Route::resource('estates.plots', 'EstatesController');
});
#THIS IS THE TESTING PART BELOW
// Event::listen('illuminate.query',function($query){
// echo '<pre style="margin:200px 80px">';
// print_r($query);
// echo '</pre>';
// });

app/models/Landlord.php
<?php

class Landlord extends \Eloquent {
	protected $primaryKey = 'id';
	protected $fillable = array('ll_personid','ll_fullname','id');
	public function person(){
		return $this->belongsTo('Person','ll_personid','id');
	}
	public function compounds(){
		return $this->hasMany('Compound','comp_landLordID','id');
	}
	public function documents(){
		return $this->hasMany('Document','entity_ID');
	}
	public function kin(){
		return $this->hasOne('Kin','ll_id','id');
	}
}

app/controllers/LandlordsController.php
<?php

class LandlordsController extends \AdminController {

	/**
	 * Display a listing of the resource.
	 * GET /landlords
	 *
	 * @return Response
	 */
	public function index()
	{
		// documents
		// 
		// $ll = Compound::with('houses.tenants')->get();
		// $ll = Landlord::with('person.contacts','compounds.houses.tenants')->whereRaw('ll_personid != ? AND deleted = ?',[0,0])->get();
		$ll = Landlord::with('person.contacts','compounds')->whereRaw('ll_personid != ? AND deleted = ?',[0,0])->get();
		$ll = ($ll)? $ll->toArray() : [];
		// var_dump($ll[9]);
		// dd( head($ll) );
		$this->layout->content = View::make('admin.Landlords.index')->with('landlords',$ll);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /landlords/create
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('admin.Landlords.create');
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /landlords
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$person = array();
		$staff = array();
		$address = array();
		$contact = array();
		$ll = array();
		$done = false;
	
		if ($input) :
			foreach ($input as $k => $table) {
				if (is_array($table)) {
					if ($k == 'person') {
						$V = new services\validators\Person($table);
						if($V->passes()){
							$person = Person::create(array(
							'pers_fname' => $table['fname'], 
							'pers_mname' => ($table['mname']) ?: null, 
							'pers_lname' => $table['lname'], 
							'pers_type' => 'Landlord', 
							'pers_DOB' => $table['dob'], 
							'pers_gender' => $table['Pers_Gender'], 
							'pers_nationality' => $table['Pers_Nationality'], 
							'pers_ethnicity' => $table['Pers_Ethnicity'], 
							'pers_NIN' => $table['nin_id'] 
							));
							if ($person->id) {
								$ll = Landlord::create(array('ll_fullname' =>$table['fname'].' '. $table['mname'] .' '. $table['lname'],'ll_personid'=>$person->id));	
								$done = true;
							}
						}else{
							$errors = $V->errors;
							return Redirect::back()->withErrors($errors)->withInput();							
						}


					}
					if ($k == 'address') {
						$address = $table;
						if ($person->id) {
							$address = array_add($address, 'Addr_EntityID', $person->id);
							$address = array_add($address, 'Addr_EntityType', 'Person');
							$V = new services\validators\Address($table);
							if($V->passes()){
								$address = Address::create($address);
							}
						}
						$errors = $V->errors;

					}
					if ($k == 'contact') {

						if ($person->id) {

							$V = new services\validators\Contact($table);
							foreach ($table as $key => $value) {
								if($V->passes()){

									if(!empty($value)){
										$contact = Contact::create(array(
										'Cont_EntityID' => $person->id,	
										'Cont_EntityType' => 'Person',	
										'Cont_Contact' => $value,	
										'Cont_ContactType' =>  $key	
										));

									$contact = $contact->toArray();
									}
								}
							}
							$errors = $V->errors;
						}
					}

				if ($k ==  'kin') {
					Kin::create(array(
						'fname' => $table['fname'],
						'mname' => $table['mname'],
						'lname' => $table['lname'],
						'contacts' => $table['contact'],
						'll_id' => $ll->id
					));
				}


				}		
			}


		if($done){


					if ($input['photo']) {

							$not = 'media'.DS.'Landlord'.DS.$person->pers_fname.'_'.$person->pers_mname.'_'.$person->pers_lname.'_'.$person->id;
							$foldername = DS.$not.DS;
							// $full_dir = $foldername.'img'.DS.'full';

							$path = base_path().$foldername ;
							$thumbnail_dir = $not.DS.'img'.DS.'thumbnail'.DS;
							$fileexten = Input::file('photo')->getClientOriginalExtension();
							$filename = Input::file('photo')->getClientOriginalName();
							// dd($path);
							$shortened = base_convert(rand(10000,99999), 10, 36);
							$rename = $person->pers_fname.'_'.$shortened.'_photo_.'.$filename;


							$filetyp = Input::file('photo')->getMimeType();

							$fileexten = Input::file('photo')->getClientOriginalExtension();
							$uploaded = false;

							if ((File::exists($path)) && ( File::exists( $path.DS.'img'.DS ) ) && ( File::exists( $path.DS.'img'.DS.'thumbnail') ) ) {

								Input::file('photo')->move($path.DS.'img'.DS, $rename);
									#notice #01
										// there was a problem when trying to resize the image. the fix is go in the project dir (html but ! include)

									// we resize (250 X 300)
									$img = Image::make($not.$rename);
									$img->resize(250 , 300);
									$img->save($thumbnail_dir.$rename);	// we move to thumnails

								// store in the database
								Document::create(array(
										'title' => 'profile picture' ,
										'entity_type' => 'Person',
										'entity_ID' => $person->id,
										'type' => 'Photo',
										'fullpath' => $path.DS.'img'.DS.$rename,
										'filename' => $filename,
										'foldername' => $not,
										'extension' => $fileexten,
										'filetype' => $filetyp,
										'thumnaildir' => $thumbnail_dir.$rename
									));
								
								# code...
							}else{
								File::exists($path) ?: mkdir($path, 0755, true);
								File::exists($path.DS.'img'.DS) ?: mkdir($path.DS.'img'.DS, 0755, true);
								File::exists($path.DS.'img'.DS.'thumbnail') ?: mkdir($path.DS.'img'.DS.'thumbnail', 0755, true);
								Input::file('photo')->move($path.DS.'img'.DS , $rename);
									// we resize (250 X 300)
									// dd($not.DS.$rename);
									$img = Image::make($not.DS.'img'.DS.$rename);
									$img->resize(250 , 300);
									$img->save($thumbnail_dir.$rename);	// we move to thumnails

								// store in the database
								Document::create(array(
										'title' => 'profile picture' ,
										'entity_type' => 'Person',
										'entity_ID' => $person->id,
										'type' => 'Photo',
										'fullpath' =>  $path.DS.'img'.DS.$rename,
										'filename' => $filename,
										'foldername' => $not,
										'extension' => $fileexten,
										'filetype' => $filetyp,
										'thumnaildir' => $thumbnail_dir.$rename
									));
							}
					} #end of photo


					if ($input['document']) {


							$not = 'media'.DS.'Landlord'.DS.$person->pers_fname.'_'.$person->pers_mname.'_'.$person->pers_lname.'_'.$person->id;
							$foldername = DS.$not.DS;
							// $full_dir = $foldername.'img'.DS.'full';
							
							$path = base_path().$foldername ;
							$fileexten = Input::file('document')->getClientOriginalExtension();
							$filename = Input::file('document')->getClientOriginalName();
							// dd($path);
							$shortened = base_convert(rand(10000,99999), 10, 36);
							$rename = $person->pers_fname.'_'.$shortened.'_document_.'.$filename;
							$filetyp = Input::file('document')->getMimeType();
							$fileexten = Input::file('document')->getClientOriginalExtension();
							$uploaded = false;

							if ( File::exists($path)  && ( File::exists( $path.DS.'document'.DS ) ) )  {

								Input::file('document')->move($path , $rename);

									#notice #01
										// there was a problem when trying to resize the image. the fix is go in the project dir (html but ! include)

									// we resize (250 X 300)
									// $img = Image::make($not.$rename);
									// $img->resize(250 , 300);
									// $img->save($thumbnail_dir.$rename);	// we move to thumnails

								// store in the database
								Document::create(array(
										'title' => $filename ,
										'entity_type' => 'Person',
										'entity_ID' => $person->id,
										'type' => 'Document',
										'fullpath' => $path.$rename,
										'filename' => $filename,
										'foldername' => $not,
										'extension' => $fileexten,
										'filetype' => $filetyp
									));
								
								# code...
							}else{
								File::exists($path) ?: mkdir($path, 0755, true);
								mkdir($path.DS.'document'.DS, 0755, true);
								Input::file('document')->move($path.DS.'document'.DS , $rename);
									// we resize (250 X 300)
									// $img = Image::make($not.$rename);
									// $img->resize(250 , 300);
									// $img->save($thumbnail_dir.$rename);	// we move to thumnails

								// store in the database
								Document::create(array(
										'title' => $filename ,
										'entity_type' => 'Person',
										'entity_ID' => $person->id,
										'type' => 'Document',
										'fullpath' => $path.$rename,
										'filename' => $filename,
										'foldername' => $not,
										'extension' => $fileexten,
										'filetype' => $filetyp
									));
							}
					} #end of document
				Flash::message("Successfully added a Landlord");
				return Redirect::back();
			}else{
				return Redirect::back()->withErrors($errors)->withInput();							
			}
		endif;
	}

	/**
	 * Display the specified resource.
	 * GET /landlords/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		#notice #001
		// check and see if the id exist in database yes procee no redirect to a lost page

		
		// $ll = Landlord::with('kin')->get();
		// $ll = Landlord::with()->whereRaw('ll_personid != ? AND deleted = ? AND id = ?',[0,0,$id])->first();
		$ll = Landlord::with('person.contacts','person.addresses','compounds.houses.tenants.person','person.documents','kin')->whereRaw('ll_personid != ? AND deleted = ? AND id = ?',[0,0,$id])->first();
		$ll = ($ll)? $ll->toArray() : [];
		// dd($ll);
		$this->layout->content = View::make('admin.Landlords.show')->with('landlord',$ll);
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /landlords/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
				$ll = Landlord::with('person.contacts','person.addresses','compounds.houses.tenants.person','person.documents','kin')->whereRaw('ll_personid != ? AND deleted = ? AND id = ?',[0,0,$id])->first();
		$ll = ($ll)? $ll->toArray() : [];
		// dd($ll['person']);

app/views/admin/Landlords/edit.blade.php
<?php #page specific processing
    $images = array();
    $person =  array();
    $documents =  array();
    $compounds = array();
    $kin = array();
    if (!empty($landlord)) {
        foreach ($landlord as $key => $value) {
           if ($key == 'person') {
              $person = $value;
           }
 
           if ($key == 'compounds') {
               $compounds = $value;
           }
           if ($key == 'kin') {
               $kin = $value;
           }
        }
    }
    $contacts = (!empty($person['contacts']))? $person['contacts'] : [];
    $addresses = (!empty($person['addresses']))? $person['addresses'] : [];


   foreach ($landlord['person'] as $d => $doc) {
	   	if ( $d == 'documents') {
		   		foreach ($doc as $dd => $val) {
		        if ($val['type'] == 'Photo') {
		           $images = $doc;
		        }else{
		            $documents[] = $doc;
		        }
	   		}
	   	}
   }
$image = last($images);
    // var_dump($image);
    // die();
    // die();
 ?>
@include('templates/top-admin')
@section('content')
   <div class="scope">
        <div class="hedacont">
            <div class="navbar">
                <div class="navbar-inner" id="scopebar">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target="navbar-responsive-collapse">
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </a>
                        <a class="brand" href="">Land lord Name : {{ucwords( $landlord['ll_fullname'] )}}</a>
                        <div class="nav-collapse collapse navbar-responsive-collapse">
                          <ul class="nav">  
                            <li><a href="{{route('land-lords.show',$landlord['id'])}}#basic">General</a> </li>
                            <li><a href="{{route('land-lords.show',$landlord['id'])}}#compounds">Properties</a> </li>
                            <li><a href="{{route('land-lords.show',$landlord['id'])}}#houses">Houses</a> </li>
                            <li><a href="{{route('land-lords.show',$landlord['id'])}}#tenants">Tenants</a> </li>
                            <!-- <li><a href="#transactions">Transactions</a></li> -->
                            <li><a href="{{route('land-lords.show',$landlord['id'])}}#payments">Payments</a></li>
                            <li><a href="{{route('land-lords.edit',$landlord['id'])}}">Edit</a> </li>
                           </ul>
                        </div><!-- /.nav-collapse -->
                    </div>
                </div><!-- /navbar-inner -->
            </div>           
        </div>  
    </div>  <!-- end of scope -->

    <div class="content-details clearfix">
    	<div class="cc clearfix">
    		<h3>Editing Land Lord</h3>
    		<hr>

	        <ul class="thumbnails">
	          <li class="row">
	            <div class="thumbnail">
	              <div class="caption">
	                <h3>Edit Personal</h3>
	                <hr>
				{{Form::model($person, ['route'=>[ 'land-lords.update' , $landlord['id']  ], 'method'=>'PATCH'],['class'=>'form-snippet'])}}

					<div class="level details">

						<div class="first">
							<div>
								{{Form::label('pers_fname','First Name')}}
								{{Form::text('pers_fname',null,['class'=>'input-xlarge','placeholder'=>'Enter first name','required'=>1])}}
							</div>
							<div>
								{{Form::label('pers_mname','Middle Name')}}
								{{Form::text('pers_mname',null,['class'=>'input-xlarge','placeholder'=>'Enter middle name'])}}
							</div>
							<div>
								{{Form::label('pers_lname','Last Name')}}
								{{Form::text('pers_lname',null,['class'=>'input-xlarge','placeholder'=>'Enter last name','required'=>1])}}
							</div>							
						</div>
					</div>
					<div class="level details">
						<span>Bio </span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('pers_DOB','Birthday ( year-month-day )')}}
								{{Form::text('pers_DOB',null,['class'=>'input-xlarge' ])}}
							</div>
							<div>
								{{Form::label('pers_ethnicity','Ethniticity')}}
								<select name="pers_ethnicity" id="enit" class="input-xlarge">
									<?php $countries = Variable::domain('Pers_Ethnicity')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select>
							</div>
							<div>
								{{Form::label('pers_nationality','Nationality')}}
								<select name="pers_nationality" id="nation" class="input-xlarge">
									<?php $countries = Variable::domain('Country')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select>
							</div>
							<div>
								{{Form::label('pers_gender','Gender')}}
								{{Form::select('pers_gender', array('male' => 'Male','female' => 'Female'));}}
							</div>
						</div>
					</div>

					<div class="level details">
						<span>Identification details</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('pers_NIN','Nation id number / passport number')}}
								{{Form::text('pers_NIN',null,['class'=>'input-xlarge span6','placeholder'=>'NIN number or passport number'])}} 
							</div>
						</div>
					</div>

	                <hr>
					{{Form::hidden('type','person')}} 
					{{Form::hidden('person_id',$person['id'])}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	              </div>
	            </div>
	            {{Form::close()}}
	          </li>  
	          
	        </ul>
	        <ul class="thumbnails">
<li class="span7">
	            <div class="thumbnail">
	              <div class="caption">
	                <h3>Edit Address</h3>
	                <hr>
						{{Form::model($person['addresses'][0], ['route'=>[ 'land-lords.update' , $person['addresses'][0]['Addr_AddressID'] ], 'method'=>'PATCH'],['class'=>'form-snippet'])}}
						<div class="level details">
							<span>Address</span>
							<hr>
							<div class="first ">
								<div>
									{{Form::label('Addr_Town','Town')}}
									{{Form::text('Addr_Town',null,['class'=>'input-xlarge','placeholder'=>'Enter town'])}}
								</div>
								<div>
									{{Form::label('Addr_District','District')}}
									<select name="Addr_District" id="region">
										<?php $countries = Variable::domain('Addr_District')->toArray();  ?>
										@foreach ($countries as $key => $country)
										<option>{{$country['Vari_VariableName']}}</option>
										@endforeach
									</select> 
								</div>
								<div>
									{{Form::label('Addr_AddressStreet','street')}}
									{{Form::text('Addr_AddressStreet',null,['class'=>'input-xlarge','placeholder'=>'Enter street'])}}
								</div>
							</div>
						</div>
	                <hr>
	                {{Form::hidden('type','address')}} 
					{{Form::hidden('address_id', $person['addresses'][0]['Addr_AddressID'] )}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	              </div>
	            </div>
	            {{Form::close()}}
	          </li> 
	          <li class="span7">
	            <div class="thumbnail">
	            	@if (isset($image['thumnaildir']))
	      				{{HTML::image($image['thumnaildir'])}}
	      			@endif
	              <div class="caption">
				{{Form::model($image, ['route'=>['land-lords.update', $landlord['id'] ], 'files'=>true,'method'=>'PATCH'],['class'=>'form-snippet'])}}
					{{Form::hidden('foldername')}}
					{{Form::hidden('fullpath')}}
					{{Form::hidden('thumnaildir')}}
					<div class="level details">
						<span>Profile picture</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('photo','Photo')}}
								{{Form::file('photo')}}
							</div>	
						</div>
					</div>

	                <hr>
					@if(isset($image['id']))
					{{Form::hidden('image_id', $image['id'])}} 
					@else
					{{Form::hidden('person_id',$person['id'])}}
					{{Form::hidden('folder',$person['pers_fname'] .'_'. $person['pers_mname'].'_'.$person['pers_lname'].'_'.$person['id'] )}} 
					@endif
	                {{Form::hidden('type','image')}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	           
	              </div>
	            </div>
	             {{Form::close()}}
	          </li>   
	        </ul>
    	</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/Landlords/index.blade.php
@include('templates/top-admin')
@section('content')
@include('__partials/modal-add-landlord')
	<div class="c-header cc">
		<h3>Landlords</h3>
	</div>
	<div class="cc">
				<div class="messages">
					@include('flash::message')
					@include('__partials/errors')
				</div>
				<table class="table">
					<thead>
						<tr>
							<th>Fullname</th>
							<th>Contacts</th>
							<th>Compounds</th>
							<th>created</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						<?php if (!empty($landlords)): ?>
							<?php foreach ($landlords as $key => $value): ?>
							<tr>
								<td>
									<a href="{{route('land-lords.show',$value['id'])}}">{{ucwords(e($value['ll_fullname']))}}</a>
								</td>
								<td>
									<?php if (!empty($value['person']['contacts'])): ?>
										<ul><?php foreach ($value['person']['contacts'] as $ind => $cont): ?>
										
												<li><span>{{e($cont['Cont_ContactType'])}} : </span> <strong>{{e($cont['Cont_Contact'])}}</strong></li>
										<?php endforeach ?></ul>
									<?php else: ?>
									N/A
									<?php endif ?>
								</td>
								<td>
									<?php if (!empty($value['compounds'])): ?>
										<ul>
											<?php foreach ( $value['compounds'] as $ind => $compound ): ?>
												<li>
													<?php if ( empty( $compound['comp_indentifier'] ) ): ?>
														<a href="{{route('houses.show',$compound['comp_id'])}}">
															# of Houses : {{$compound['comp_numberOfHouses']}}
														</a>
														<?php else: ?>
														<a href="{{ route('compounds.show',$compound['comp_id']) }} ">
															{{ ucwords( $compound['comp_indentifier'] ) }}
														</a>
													<?php endif ?>
												</li>
											<?php endforeach ?>
										</ul>
										<?php else: ?>
										no compounds
									<?php endif; ?>
								</td>
								<td>
									{{e($value['created_at'])}}
								</td>

								<td class="actions">
									<a href="{{route('land-lords.show',$value['id'])}}">view</a> |
									
								<a href="#" class="dropdown-toggle"  data-toggle="dropdown">
									Options
									<!-- <span class="caret"></span> -->
								</a>
								  <ul class="dropdown-menu">
								    <!-- dropdown menu links -->
								    <li><a href="{{route('land-lords.edit',$value['id'])}}">edit</a></li>
								    <!-- <li><a href="{{route('compounds.edit',$value['id'])}}">add Compound to</a></li> -->
								    <li>
								    	{{Form::delete('land-lords/'. $value['id'], 'Delete')}}
								    </li>
								  </ul>
								</td>
							</tr>						
							<?php endforeach ?>
							<?php else: ?>
							<tr>
								<td colspan="8"><h4>No Land lords Available!</h4></td>
							</tr>
						<?php endif ?>
					</tbody>
				</table>

		  </div>
		</div>
	</div>
@stop
@include('templates/bottom-admin')