app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');
Route::resource('/','WelcomeController');
Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');
Route::get('download',function(){
	$file = $_GET['file'];
	return Response::download($file);
});
Route::get('view', function()
{
	$file = $_GET['file'];
	return Redirect::to($file);
});

// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){
Route::resource('users','UsersController');
Route::resource('admin','AdminController');
Route::resource('admin.staffs','StaffsController');
Route::resource('admin.plots','PlotsController');
Route::resource('plots','PlotsController');
Route::resource('agents','AgentsController');
Route::resource('staffs','StaffsController');
Route::resource('payments','PaymentsController');
Route::resource('customers.payments','PaymentsController');
Route::resource('cocuments', 'DocumentsController');
Route::resource('customers', 'CustomersController');
Route::resource('agents.customers', 'CustomersController');
Route::resource('search', 'SearchController');
Route::resource('partners', 'PartnersController');
Route::resource('transactions', 'TransactionsController');
Route::resource('prospectives', 'ProspectivesController');
Route::resource('tenants', 'TenantsController');
Route::resource('tenants.payments', 'TenanPaymentsController');
Route::resource('land-lords', 'LandlordsController');
Route::resource('compounds', 'CompoundsController');
Route::resource('houses', 'HousesController');
Route::resource('notifications', 'NotificationsController');
Route::get('data-entry', array('as'=>'data_entry', 'uses'=>'PagesController@showData'));
Route::resource('estates', 'EstatesController');
Route::resource('estates.plots', 'EstatesController');
});
#THIS IS THE TESTING PART BELOW
// Event::listen('illuminate.query',function($query){
// echo '<pre style="margin:200px 80px">';
// print_r($query);
// echo '</pre>';
// });

app/controllers/HousesController.php
<?php

class HousesController extends \AdminController {

	/**
	 * Display a listing of the resource.
	 * GET /houses
	 *
	 * @return Response
	 */
	public function index()
	{
		// $all = Compound::with('houses')->get();
		$all = House::with('compound.landlord')->get();
		$all = ($all) ? $all->toArray() : [];
		$this->layout->content = View::make('admin.Houses.index')->with('houses',$all);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /houses/create
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('admin.Houses.create');
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /houses
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		// no validation
		$house = House::create(array(
		'hous_compoundID'=> $input['house_compound'],
		'hous_advance'=> $input['house_advance'],
		'hous_price'=> $input['house_price'],
		'hous_description'=> $input['house_remarks'],
		'hous_number'=> $input['house_number'],
		'hous_numberOfrooms'=> $input['room_number']
		));

		if( $house ){
				Flash::message("Successfully added a House");
				return Redirect::back();
			}else{
				return Redirect::back()->withErrors($errors)->withInput();							
			}
	}

	/**
	 * Display the specified resource.
	 * GET /houses/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		// ->with('houses',$all)
		$house = House::with('compound','tenants.person')->first();
		$house = (!empty($house)) ? $house->toArray() : [];
		// dd($house);
		$this->layout->content = View::make('admin.Houses.show')->with('house', $house);
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /houses/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('admin.Houses.edit');
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /houses/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = Input::all();
		$house = House::find($id);
		$house->fill($input);
		$house->save();
		return Redirect::back();
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /houses/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		House::destroy($id);
		return Redirect::back();
	}

}

app/views/admin/Houses/create.blade.php
@include('templates/top-admin')
@section('content')
	<div class="cc">
		<div class="create-Plot">
			<div class="form-snippet">
				<div class="form-header">
					<div class="title">
						<h2>Add a new house </h2>
					</div>
				</div>
				<div class="messages">
					@include('flash::message')
					@include('__partials/errors')
				</div>
				{{Form::open(['route'=>'houses.store'],[],['class'=>'form-snippet'])}}
					<div class="level name">

						<div>
							{{Form::label('house_number','House number')}}
							{{Form::text('house_number',null,['class'=>'input-xlarge span6','placeholder'=>'House Number'])}}
						</div>
						<div>
							{{Form::label('room_number','Number of rooms')}}
							{{Form::number('room_number',['class'=>'input-xlarge span6','placeholder'=>'number of rooms','step'=>'any'])}}
						</div>
					</div>
					<div class="level name">
						<div>
							{{Form::label('house_price','Price')}}
							{{Form::text('house_price',null,['class'=>'input-xlarge span6','placeholder'=>'House price per month'])}}
						</div>
						<div>
							{{Form::label('house_advance','Advance Amount')}}
							{{Form::number('house_advance',['class'=>'input-xlarge span6','placeholder'=>'Advance payment','step'=>'any'])}}
						</div>
					</div>
					<div class="level name">
						<div>
							{{Form::label('house_compound','Compound')}}
							<?php
								 $comps = Compound::all();
								 $compounds = ($comps)? $comps->toArray() : [];
							?>
							<select class="span12" name="house_compound">
								<?php if (!empty($compounds)): ?>
									<?php foreach ($compounds as $key => $value): ?>

										<option value="{{$value['comp_id']}}">
											{{$value['comp_indentifier']}}
										</option>
									<?php endforeach ?>

								
									<?php else: ?>
								<option value="0">No compound</option>	
								<?php endif ?>
								

							</select>
						</div>


					</div>
					<div class="level">
						<div>
							{{Form::label('house_descriptions','Description')}}
							{{Form::textarea('house_remarks',null,['class'=>'input-xlarge span12','placeholder'=>'Enter your Description here'])}}
						</div>
					</div>
					<div class="level actions">
						<div>
							  <button type="submit" class="btn btn-large btn-primary span12" name="save" value="save">Add House</button>
						</div>
					</div>
				{{Form::close()}}
			</div>
		</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/Houses/edit.blade.php
<?php #page specific processing
    $image = array();
    $person =  array();
    $documents =  array();
    $compounds = array();
    $kin = array();
    if (!empty($landlord)) {
        foreach ($landlord as $key => $value) {
           if ($key == 'person') {
              $person = $value;
           }
           if ($key == 'documents') {
               foreach ($value as $d => $doc) {
                    if ($doc['type'] == 'Photo') {
                       $image = $doc;
                    }else{
                        $documents[] = $doc;
                    }
               }
           }
           if ($key == 'compounds') {
               $compounds = $value;
           }
           if ($key == 'kin') {
               $kin = $value;
           }
        }
    }
    $contacts = (!empty($person['contacts']))? $person['contacts'] : [];
    $addresses = (!empty($person['addresses']))? $person['addresses'] : [];

    if (!empty($person['documents'])) {
       foreach ($person['documents'] as $d => $doc) {
            if ($doc['type'] == 'Photo') {
               $image = $doc;
            }else{
                $documents[] = $doc;
            }
       }
    }
    // var_dump($image);
    // die();
 ?>
@include('templates/top-admin')
@section('content')
   <div class="scope">
        <div class="hedacont">
            <div class="navbar">
                <div class="navbar-inner" id="scopebar">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target="navbar-responsive-collapse">
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </a>
                        <a class="brand" href="">Land lord Name : {{ucwords( $landlord['ll_fullname'] )}}</a>
                        <div class="nav-collapse collapse navbar-responsive-collapse">
                          <ul class="nav">  
                            <li><a href="{{route('land-lords.show',$landlord['id'])}}#basic">General</a> </li>
                            <li><a href="{{route('land-lords.show',$landlord['id'])}}#compounds">Properties</a> </li>
                            <li><a href="{{route('land-lords.show',$landlord['id'])}}#houses">Houses</a> </li>
                            <li><a href="{{route('land-lords.show',$landlord['id'])}}#tenants">Tenants</a> </li>
                            <!-- <li><a href="#transactions">Transactions</a></li> -->
                            <li><a href="{{route('land-lords.show',$landlord['id'])}}#payments">Payments</a></li>
                            <li><a href="{{route('land-lords.edit',$landlord['id'])}}">Edit</a> </li>
                           </ul>
                        </div><!-- /.nav-collapse -->
                    </div>
                </div><!-- /navbar-inner -->
            </div>           
        </div>  
    </div>  <!-- end of scope -->

    <div class="content-details clearfix">
    	<div class="cc clearfix">
    		<h3>Editing Land Lord</h3>
    		<hr>

	        <ul class="thumbnails">
	          <li class="row">
	            <div class="thumbnail">
	              <div class="caption">
	                <h3>Edit Personal</h3>
	                <hr>
				{{Form::model($person, ['route'=>[ 'land-lords.update' , $landlord['id']  ], 'method'=>'PATCH'],['class'=>'form-snippet'])}}

					<div class="level details">

						<div class="first">
							<div>
								{{Form::label('pers_fname','First Name')}}
								{{Form::text('pers_fname',null,['class'=>'input-xlarge','placeholder'=>'Enter first name','required'=>1])}}
							</div>
							<div>
								{{Form::label('pers_mname','Middle Name')}}
								{{Form::text('pers_mname',null,['class'=>'input-xlarge','placeholder'=>'Enter middle name'])}}
							</div>
							<div>
								{{Form::label('pers_lname','Last Name')}}
								{{Form::text('pers_lname',null,['class'=>'input-xlarge','placeholder'=>'Enter last name','required'=>1])}}
							</div>							
						</div>
					</div>
					<div class="level details">
						<span>Bio </span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('pers_DOB','Birthday ( year-month-day )')}}
								{{Form::text('pers_DOB',null,['class'=>'input-xlarge' ])}}
							</div>
							<div>
								{{Form::label('pers_ethnicity','Ethniticity')}}
								<select name="pers_ethnicity" id="enit" class="input-xlarge">
									<?php $countries = Variable::domain('Pers_Ethnicity')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select>
							</div>
							<div>
								{{Form::label('pers_nationality','Nationality')}}
								<select name="pers_nationality" id="nation" class="input-xlarge">
									<?php $countries = Variable::domain('Country')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select>
							</div>
							<div>
								{{Form::label('pers_gender','Gender')}}
								{{Form::select('pers_gender', array('male' => 'Male','female' => 'Female'));}}
							</div>
						</div>
					</div>

					<div class="level details">
						<span>Identification details</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('pers_NIN','Nation id number / passport number')}}
								{{Form::text('pers_NIN',null,['class'=>'input-xlarge span6','placeholder'=>'NIN number or passport number'])}} 
							</div>
						</div>
					</div>

	                <hr>
					{{Form::hidden('type','person')}} 
					{{Form::hidden('person_id',$person['id'])}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	              </div>
	            </div>
	            {{Form::close()}}
	          </li>  
	          
	        </ul>
	        <ul class="thumbnails">
<li class="span7">
	            <div class="thumbnail">
	              <div class="caption">
	                <h3>Edit Address</h3>
	                <hr>
						{{Form::model($person['addresses'][0], ['route'=>[ 'land-lords.update' , $person['addresses'][0]['Addr_AddressID'] ], 'method'=>'PATCH'],['class'=>'form-snippet'])}}
						<div class="level details">
							<span>Address</span>
							<hr>
							<div class="first ">
								<div>
									{{Form::label('Addr_Town','Town')}}
									{{Form::text('Addr_Town',null,['class'=>'input-xlarge','placeholder'=>'Enter town'])}}
								</div>
								<div>
									{{Form::label('Addr_District','District')}}
									<select name="Addr_District" id="region">
										<?php $countries = Variable::domain('Addr_District')->toArray();  ?>
										@foreach ($countries as $key => $country)
										<option>{{$country['Vari_VariableName']}}</option>
										@endforeach
									</select> 
								</div>
								<div>
									{{Form::label('Addr_AddressStreet','street')}}
									{{Form::text('Addr_AddressStreet',null,['class'=>'input-xlarge','placeholder'=>'Enter street'])}}
								</div>
							</div>
						</div>
	                <hr>
	                {{Form::hidden('type','address')}} 
					{{Form::hidden('address_id', $person['addresses'][0]['Addr_AddressID'] )}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	              </div>
	            </div>
	            {{Form::close()}}
	          </li> 
	          <li class="span7">
	            <div class="thumbnail">
      			{{HTML::image($image['thumnaildir'])}}
	              <div class="caption">
				{{Form::model($image, ['route'=>['land-lords.update', $landlord['id'] ], 'files'=>true,'method'=>'PATCH'],['class'=>'form-snippet'])}}
					{{Form::hidden('foldername')}}
					{{Form::hidden('fullpath')}}
					{{Form::hidden('thumnaildir')}}
					<div class="level details">
						<span>Profile picture</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('photo','Photo')}}
								{{Form::file('photo')}}
							</div>	
						</div>
					</div>

	                <hr>
	                {{Form::hidden('type','image')}} 
					{{Form::hidden('image_id', $image['id'])}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	           
	              </div>
	            </div>
	             {{Form::close()}}
	          </li>   
	        </ul>
    	</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/Houses/index.blade.php
@include('templates/top-admin')
@section('content')
@include('__partials/modal-add-house')
	<div class="c-header cc">
		<h3>Houses <!-- <a href="#myModal" role="button" data-toggle="modal"><i class="fa fa-plus"></i></a> --></h3>
	</div>
	<div class="cc">
				<div class="messages">
					@include('flash::message')
					@include('__partials/errors')
				</div>
				<table class="table">
					<thead>
						<tr>
							<th>House</th>
							<th>Compound</th>
							<th>Price</th>
							<th>Description</th>
							<th>Available</th>
							<th>created</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						<?php if (!empty($houses)): ?>
							<?php foreach ($houses as $key => $value): ?>
							<tr>
							<td><a href="{{route('houses.show',$value['hous_id'])}}">{{$value['hous_number']}}</a></td>
							<td><a href="{{route('compounds.show',$value['compound']['comp_id'])}}">{{$value['compound']['comp_indentifier']}}</a></td>
								<td>{{$value['hous_price']}}</td>
								<td>{{$value['hous_description']}}</td>
								<td><?php echo ($value['hous_availability']) ?: 'occupied' ?></td>
								<td>{{$value['created_at']}}</td>
								<td>
									<a href="{{route('houses.show',$value['hous_id'])}}">view </a>| 
									<a href="{{route('houses.destroy',$value['hous_id'])}}" class="dropdown-toggle"  data-toggle="dropdown">
										Options
										<!-- <span class="caret"></span> -->
									</a>
									  <ul class="dropdown-menu">
									    <!-- dropdown menu links -->
									    <li>
									    	{{Form::delete('houses/'. $value['hous_id'], 'Delete')}}
									    </li>
									  </ul>
								</td>
							</tr>						
							<?php endforeach ?>
							<?php else: ?>
							<tr>
								<td colspan="10"><h4>No Houses Available!</h4></td>
							</tr>
						<?php endif ?>
					</tbody>
				</table>

		  </div>
		</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/Houses/show.blade.php
<?php #page specific processing

$tenants = array();
$tenants = array();
$payments = array();
 $comps = Compound::all();
 $compounds = ($comps)? $comps->toArray() : [];
// dd($compounds);
// die();
 ?>
@include('templates/top-admin')
@section('content')
@include('__partials/modal-edit-house')
   <div class="scope">
        <div class="hedacont">
            <div class="navbar">
                <div class="navbar-inner" id="scopebar">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target="navbar-responsive-collapse">
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </a>
                        <a class="brand" href="#">House Number : <?php echo (!empty($house['hous_number']))? $house['hous_number'] : 'No number'; ?></a>
                        <div class="nav-collapse collapse navbar-responsive-collapse">
                          <ul class="nav">  
                            <li><a href="{{route('houses.show',$house['hous_id'])}}#details">Details</a> </li>
                            <li><a href="{{route('houses.show',$house['hous_id'])}}#tenants">Tenants</a> </li>
                            <li><a href="{{route('houses.show',$house['hous_id'])}}#payments">Payments</a></li>
                            <li><a href="#edit-house" role="button" data-toggle="modal">Edit</a></li>
                           </ul>
                        </div><!-- /.nav-collapse -->
                    </div>
                </div><!-- /navbar-inner -->
            </div>            
        </div>  
    </div>  <!-- end of scope -->

    <div class="content-details clearfix">
  <div class="cc clearfix" id="details">
    <h3>House details</h3>
    <hr>
    <table class="table">
      <thead>
        <tr>
            <th>Number</th>
            <th>Price</th>
            <th>House advance</th>
            <th>Available</th>
            <th>Number of rooms</th>
            <th>Description</th>
            <th>created</th>
        </tr>
      </thead>
      <tbody>
        <?php if (!empty($house)): ?>

            <tr>
                <td>{{ucfirst($house['hous_number'])}}</td> 
                <td>{{ucfirst($house['hous_price'])}}</td> 
                <td>{{ucfirst($house['hous_advance'])}}</td> 
                <td>{{ucfirst($house['hous_availability'])}}</td> 
                <td>{{ucfirst($house['hous_numberOfrooms'])}}</td> 
                <td>{{ucfirst($house['hous_description'])}}</td> 
                <td>{{ucfirst($house['created_at'])}}</td> 
            </tr>                                              
        <?php else: ?>
        <tr><td colspan="8"><h4>no house details yet!</h4></td></tr>
        <?php endif ?>
      </tbody>
    </table>
  </div>
   <div class="cc clearfix" id="tenants">
        <h3>Tenants</h3>
    <hr>
    <table class="table">
      <thead>
        <tr>
            <th>Fullname</th>
            <th>Gender</th>
            <th>D.O.B</th>
            <th>Nationality</th>
            <td>Status</td>
            <th>Tent advance</th>
            <th>Monthly fee</th>
            <th>created</th>
        </tr>
      </thead>
      <tbody>
        <?php if (!empty($house['tenants'])): ?>
          <?php foreach ($house['tenants'] as $t => $tenant): ?>
            <tr>
                <td><a href="{{route('tenants.show',$tenant['tent_id'])}}"><?php echo ucfirst($tenant['person']['pers_fname'].' '.$tenant['person']['pers_mname'].' '.$tenant['person']['pers_lname']) ?></a></td>
                <td>{{$tenant['person']['pers_gender']}}</td>
                <td>{{$tenant['person']['pers_DOB']}}</td>
                <td>{{$tenant['person']['pers_nationality']}}</td>
                <td><?php if ($tenant['tent_status'] == 0): ?>
                  Vacated
                <?php else: ?>
                  <?php if ( $tenant['tent_status'] == 1 ): ?>
                     Occupant
                  <?php endif ?>
                  <?php if ( $tenant['tent_status'] == 2 ): ?>
                     Pending to Leave
                  <?php endif ?>
                  <?php if ( $tenant['tent_status'] == 3 ): ?>
                     Vacated but owing
                  <?php endif ?>
                <?php endif ?></td>
                <td>{{$tenant['tent_advance']}}</td>
                <td>{{$tenant['tent_monthlyFee']}}</td>
                <td>{{$tenant['created_at']}}</td>
            </tr>                                    
            <?php endforeach ?>  
        <?php else: ?>
        <tr><td colspan="8"><h4>no tenants details yet!</h4></td></tr>
        <?php endif ?>
      </tbody>
    </table>
   </div>
   <div class="cc clearfix" id="payments">
        <h3>Payments</a></h3>
    <hr>
    <table class="table">
      <thead>
        <tr>
            <th>Amount</th>
            <th>For : </th>
            <th>Payment Date</th>
            <th>Paid by</th>
            <th>Track</th>
            <th>Description</th>
            <th>updated</th>
            <th>created</th>
        </tr>
      </thead>
      <tbody>
        <?php if (!empty($customer['plots'])): ?>
          <?php foreach ($customer['plots'] as $key => $plot): ?>
            <tr>
                <td>{{$plot['plot_name']}}</td>
                <td>{{$plot['plot_number']}}</td>
                <td>{{$plot['plot_size']}}</td>
                <td>{{$plot['plot_price']}}</td>
                <td>{{$plot['plot_location']}}</td>
                <td>{{$plot['plot_status']}}</td>
                <td>{{$plot['plot_availability']}}</td>
                <td>{{$plot['plot_remarks']}}</td>
                <td>{{$plot['created_at']}}</td>
                <td><a href="{{route('plots.show',$plot['plot_id'])}}">view</a> | <a href="#">options</a></td>
            </tr>                                                
            <?php endforeach ?>  
        <?php else: ?>
       <tr><td colspan="8"><h4>no payments yet!</h4></td></tr>
        <?php endif ?>
      </tbody>
    </table>
   </div>
</div>


@stop
@include('templates/bottom-admin')