app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');
Route::resource('/','WelcomeController');
Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');
Route::get('download',function(){
	$file = $_GET['file'];
	return Response::download($file);
});
Route::get('view', function()
{
	$file = $_GET['file'];
	return Redirect::to($file);
});

// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){
Route::resource('users','UsersController');
Route::resource('admin','AdminController');
Route::resource('admin.staffs','StaffsController');
Route::resource('admin.plots','PlotsController');
Route::resource('plots','PlotsController');
Route::resource('agents','AgentsController');
Route::resource('staffs','StaffsController');
Route::resource('payments','PaymentsController');
Route::resource('customers.payments','PaymentsController');
Route::resource('cocuments', 'DocumentsController');
Route::resource('customers', 'CustomersController');
Route::resource('agents.customers', 'CustomersController');
Route::resource('search', 'SearchController');
Route::resource('partners', 'PartnersController');
Route::resource('transactions', 'TransactionsController');
Route::resource('prospectives', 'ProspectivesController');
Route::resource('tenants', 'TenantsController');
Route::resource('tenants.payments', 'TenanPaymentsController');
Route::resource('land-lords', 'LandlordsController');
Route::resource('compounds', 'CompoundsController');
Route::resource('houses', 'HousesController');
Route::resource('notifications', 'NotificationsController');
Route::get('data-entry', array('as'=>'data_entry', 'uses'=>'PagesController@showData'));
Route::resource('estates', 'EstatesController');
Route::resource('estates.plots', 'EstatesController');
});
#THIS IS THE TESTING PART BELOW
// Event::listen('illuminate.query',function($query){
// echo '<pre style="margin:200px 80px">';
// print_r($query);
// echo '</pre>';
// });

app/models/Compound.php
<?php

class Compound extends \Eloquent {
	protected $primaryKey = 'comp_id';
	protected $fillable = [
	'comp_id',
	'comp_landLordID',
	'comp_numberOfHouses',
	'comp_size',
	'comp_remarks',
	'location',
	'comp_indentifier',
	'name',
	'agendid'
	];


	public function scopeAvailable($query){
		return $query->whereRaw('deleted != ? AND comp_landLordID = ?',[0,0])->get();
	}

	public function landlord(){
		return $this->belongsto('Landlord','comp_landLordID','id');
	}
	public function houses(){
		return $this->hasMany('House','hous_compoundID','comp_id');
	}
	public function agent(){
		return $this->belongsTo('Agent','agendid','agen_id');
	}
}

app/controllers/CompoundsController.php
<?php
	/** Topics
		1. Notices
			- no validation 
	 * 			#notice 01
	 *  
	 *
	 * @return Response {}
	 */
class CompoundsController extends \AdminController {

	/**
	 * Display a listing of the resource.
	 * GET /compounds
	 *
	 * @return Response
	 */
	public function index()
	{
		$all = Compound::with('landlord')->get();
		$all = ($all) ? $all->toArray() : [];
		$this->layout->content = View::make('admin.Compounds.index')->with('compounds',$all);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /compounds/create
	 *
	 * @return Response
	 */
	public function create()
	{
		$agents = Agent::with('person')->get();
		$agents = (!empty($agents))? $agents->toArray() : [];
		// dd($agents);
		$this->layout->content = View::make('admin.Compounds.create',compact('agents'));
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /compounds
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();

		if(Request::ajax()):
			$data = array();
			$fname = '';
			$mname = '';
			$lname = '';
			$keywords = [];
			if (str_contains($input['fullname'], ' ')) {
				
				$keywords = preg_split("/[\s]+/", trim($input['fullname']));
				// $t = count($keywords);
				// if ( $t > 2) {
				// 	for($i = 0; $i >= $t; $i++){
				// 		if ($i != 0 && $i != $t) {
				// 			$mname .= $keywords[$i].' ';
				// 		}else{
				// 			if($i != 0){
				// 				$fname .= $keywords[$i];	
				// 			}else{
				// 				$lname .= $keywords[$i];	
				// 			}
				// 		}
				// 	}
				// }
			}
			$person = Person::create(array(
					'pers_fname'=> (head($keywords)) ?: '',
					'pers_mname'=> ($keywords[1]) ?: '',
					'pers_lname'=> (last($keywords)) ?: '',
					'pers_type'=> 'Landlord'
			));
			$ll = Landlord::create(array('ll_fullname' =>$input['fullname'],'ll_personid'=>$person->id));
			$data['compound'] = Compound::create(array(
				'comp_landLordID' => $ll->id,
				'comp_numberOfHouses' => e($input['Compound_houses']),
				'location' => e($input['Compound_location'])
			));

			$data['contact'] = Contact::create(array(
				'Cont_EntityID' => $person->id,	
				'Cont_EntityType' => 'Person',	
				'Cont_Contact' => e($input['contacts']),	
				'Cont_ContactType' =>  'Phone'
			));

			$data['address'] = Address::create(array(
				 'Addr_EntityID' => $person->id,	
				 'Addr_EntityType' => 'Person', 
				 'Addr_AddressStreet' => e($input['address']),				
			));
			$data['landlord'] = $ll;
			return Response::json( $data );
		endif;
		if( isset($input['agent_id']) ):
			$compound =  Compound::create(array(
				'comp_numberOfHouses'=> $input['comp_houses'],
				'comp_landLordID' => $input['ll_id'],
				'name' => $input['property_name'],
				'comp_remarks'=> $input['comp_remarks'],
				'location'=> $input['comp_location'],
				'comp_indentifier'=> $input['comp_number'],		
				'agendid'=> $input['agent_id']	
			));
		else:
			$compound =  Compound::create(array(
				'comp_numberOfHouses'=> $input['comp_houses'],
				'comp_landLordID' => $input['ll_id'],
				'name' => $input['property_name'],
				'comp_remarks'=> $input['comp_remarks'],
				'location'=> $input['comp_location'],
				'comp_indentifier'=> $input['comp_number']		
			));
		endif;
		#notice 0.1
		// add compound v0.0.1 #no validation

		if( $compound ){

				Flash::message("Successfully added a Compound");
				return Redirect::back();
			}else{
				return Redirect::back()->withErrors($errors)->withInput();							
			}
	}

	/**
	 * Display the specified resource.
	 * GET /compounds/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		#notice 003 
		// check for the id in the database
		$compound = Compound::with('landlord','houses.tenants.person','agent.person')->where('comp_id','=',$id)->first();
		$compound = ($compound)? $compound->toArray() : [];
		// // var_dump($ll[9]);
		// dd(($compound));
		$this->layout->content = View::make('admin.Compounds.show')->with('compound',$compound);
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /compounds/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /compounds/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		#notice 005 this is a big loop hole rics
		$input = Input::all();
		$compound = Compound::find($id);
		$compound->fill($input);
		$compound->save();
		return Redirect::back();
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /compounds/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Compound::destroy($id);
		return Redirect::back();
	}

}

app/views/admin/Compounds/create.blade.php
<?php #page specific processing
$ll = Landlord::all();
// $ll = (!empty($ll))? $ll->toArray() : [];
 ?>
@include('templates/top-admin')
@section('content')
	<div class="cc">
		<div class="create-comp">
			<div class="form-snippet">
				<div class="form-header">
					<div class="title">
						<h2>Add a new Property </h2>
					</div>
				</div>
				<div class="messages">
					@include('flash::message')
					@include('__partials/errors')
				</div>
				{{Form::open(['route'=>'compounds.store'],[],['class'=>'form-snippet'])}}
				<div class="level name">
						<div>
							{{Form::label('property_name','Property Name')}}
							{{Form::text('property_name',null,['class'=>'input-xlarge span6','placeholder'=>'Enter property name','step'=>'any'])}}
						</div>
						<div>
							{{Form::label('comp_location','Property location')}}
							{{Form::text('comp_location',null,['class'=>'input-xlarge span6','placeholder'=>'Property location or Adress'])}}
						</div>
				</div>
					<div class="level name">


						<div>
							{{Form::label('comp_houses','Number of houses')}}
							{{Form::number('comp_houses',['class'=>'input-xlarge span6','placeholder'=>'Compound number of houses','step'=>'any'])}}
						</div>

						<div>
							{{Form::label('comp_number','Compound number')}}
							{{Form::text('comp_number',null,['class'=>'input-xlarge span6','placeholder'=>'Compound number or Indentifier'])}}
						</div>
					</div>
					<div class="level name">
						<div class="span6">
							{{Form::label('ll_id','Land Lord')}}
							<select name="ll_id" class="input-xlarge span6">
								<?php if (!empty($ll)): ?>
									<?php foreach ($ll as $key => $value): ?>
										<option value="{{$value->id}}">{{$value->ll_fullname}}</option>
									<?php endforeach ?>
									<?php else: ?>
									<option>not available</option>
								<?php endif ?>
								
							</select>
						</div>
						<div>
							{{Form::label('agent_id','Agent Assigned')}}
							<select name="agent_id" class="input-xlarge span6">
								<?php if (!empty($agents)): ?>
									<?php foreach ($agents as $key => $value): ?>
										<option value="{{$value['agen_id']}}">{{$value['person']['pers_fname'].' '.$value['person']['pers_mname'].' '.$value['person']['pers_lname']}}</option>
									<?php endforeach ?>
									<?php else: ?>
									<option>not available</option>
								<?php endif ?>
								
							</select>
						</div>

					</div>
					<div class="level">
						<div>
							{{Form::label('comp_remarks','Compound Remarks')}}
							{{Form::textarea('comp_remarks',null,['class'=>'input-xlarge span12','placeholder'=>'Enter your remarks here'])}}
						</div>
					</div>
					<div class="level actions">
						<div>
							  <button type="submit" class="btn btn-large btn-primary span12" name="save" value="save">Create Compound</button>
						</div>
					</div>
				{{Form::close()}}
			</div>
		</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/Compounds/edit.blade.php
C:\wamp\www\universal\app/views/Compounds/edit.blade.php

app/views/admin/Compounds/index.blade.php
@include('templates/top-admin')
@section('content')
@include('__partials/modal-add-compound')
	<div class="c-header cc">
		<h3>Compounds</h3>
	</div>
	<div class="cc">
				<div class="messages">
					@include('flash::message')
					@include('__partials/errors')
				</div>
				<table class="table">
					<thead>
						<tr>
							<th>Name</th>
							<th>Owner</th>
							<th>Houses</th>
							<th>Remarks</th>
							<th>created</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						<?php if (!empty($compounds)): ?>
							<?php foreach ($compounds as $key => $value): ?>
							<tr>
								<td>{{ucfirst($value['name'])}}</td>
								<td>
									<?php if ($value['landlord']): ?>
										<a href="{{route('land-lords.show',$value['landlord']['id'])}}">{{ucwords(e($value['landlord']['ll_fullname']))}}</a>
										<?php else: ?>
										No owner
									<?php endif ?>
								</td>
								<td>	
									{{$value['comp_numberOfHouses']}}
								</td>
								<td>	
									{{$value['comp_remarks']}}
								</td>
								<td>	
									{{$value['created_at']}}
								</td>
								<td>	
									<a href="{{route('compounds.show',$value['comp_id'])}}">view</a> |
									<a href="{{route('compounds.destroy',$value['comp_id'])}}" class="dropdown-toggle"  data-toggle="dropdown">
										Options
										<!-- <span class="caret"></span> -->
									</a>
									  <ul class="dropdown-menu">
									    <!-- dropdown menu links -->
									    <li>
									    	{{Form::delete('compounds/'. $value['comp_id'], 'Delete')}}
									    </li>
									  </ul>
								</td>
							</tr>						
							<?php endforeach ?>
							<?php else: ?>
							<tr>
								<td colspan="8"><h4>No Compounds Available!</h4></td>
							</tr>
						<?php endif ?>
					</tbody>
				</table>

		  </div>
		</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/Compounds/show.blade.php
<?php #page specific processing
$ll = Landlord::all();
	$agents = Agent::with('person')->get();
	$agents = (!empty($agents))? $agents->toArray() : [];

 ?>
@include('templates/top-admin')
@section('content')
@include('__partials/modal-edit-compound')
	<div class="c-header cc">
		<h3><?php echo (!empty($compound['name']))? ucwords($compound['name']): 'No compound name';  ?></h3>
		<hr>
		<div class="stats">
			<?php if (!empty($compound['landlord'])): ?>
				<a href="{{route('land-lords.show',$compound['landlord']['id'] )}}"><?php echo ($compound['landlord']['ll_fullname'] )? : 'No landlord';?></a> | 
			<?php endif ?>
			<?php if (!empty($compound['landlord'])): ?>
				<span>{{$compound['created_at']}}</span> |
				<span>{{$compound['updated_at']}}</span> |
				 <a href="#edit-compound" role="button" data-toggle="modal">Edit</a>		
			<?php endif ?>	
		</div>
	</div>
	<div class="cc">
		<table class="table">
			<thead>
				<tr>
					<th>House</th>
					<th>House price</th>
					<th>House availability</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<?php if (!empty($compound['houses'])): ?>
				<?php foreach ($compound['houses'] as $h => $house): ?>
					<tr>
						<td>{{$house['hous_number']}}</td>
						<td>{{$house['hous_price']}}</td>
						<td>{{$house['hous_availability']}}</td>
						<td><a href="{{route('houses.show',$house['hous_id'])}}">view</a></td>
					</tr>					
				<?php endforeach ?>
						
					<?php else: ?>
					<tr>
						<td colspan="7"><h4>No Houses Available!</h4></td>
					</tr>
				<?php endif ?>
			</tbody>
		</table>
	</div>
@stop
@include('templates/bottom-admin')